Fixes and updates
Pacane/SlackHistoryKeeper pull request #15
Opened 2016-10-04 20:05 UTC by meriouma

- Update dependencies
- Fixed angular 2
- Changed emoticons provider
- Added "mention:"

2016-10-04 20:18 UTC, Pacane requested changes

2016-10-04 20:18 UTC, Pacane commented on frontend/lib/emojis/emojis.dart
> +    String utf16 = (emoji['char'] as String)?.codeUnits?.fold(
`(prev, value) => '$prev ${value.toRadixString(16)}')`

2016-10-04 20:18 UTC, Pacane commented on frontend/lib/emojis/emojis.dart
> +    if (textString.length == 0) {
`isEmpty`

2016-10-04 20:18 UTC, Pacane commented on frontend/lib/emojis/emojis.dart
> +        if (0xDC00 <= b && b <= 0xDFFF) {
wtf esti lol

2016-10-04 20:18 UTC, Pacane commented on frontend/lib/services/message_parser.dart
> +class MessageParser
dartfmt

2016-10-04 20:18 UTC, Pacane commented on frontend/lib/services/message_parser.dart
>    List<InlineSyntax> inlineSyntaxes = [];
`List<InlineSyntax> inlineSyntaxes = <InlineSyntax>[];`

2016-10-04 20:18 UTC, Pacane commented on frontend/lib/services/message_parser.dart
>      inlineSyntaxes = [
`= <InlineSyntax>` [ ... ];`

2016-10-04 20:18 UTC, Pacane commented on frontend/lib/services/message_parser.dart
>      inlineSyntaxes = [
t'es pas obligé mais le strong mode aime mieux ça pour t'aider.

2016-10-04 20:18 UTC, Pacane commented on frontend/lib/services/message_parser.dart
> +    var mention = new Element.text('strong', '@' + user.name);
string interpolation

2016-10-04 20:18 UTC, Pacane commented on frontend/lib/services/query_parser.dart
> +        expressions.where((String exp) => exp.startsWith('from:')).map((token) {
moi je mettrais les `from:` `mention:` pis tout ça dans des constantes, pis j'utiliserais leur length pour le substring.

2016-10-04 20:18 UTC, Pacane commented on shared/pubspec.yaml
> +  dart_style: 0.2.4
Ça sert à quoi d'ajouter ça ici? tu t'en sers pour quoi?

2016-10-04 20:20 UTC, Pacane commented
As-tu réussi à faire builder le projet correctement? Je sais que redstone et di.dart ont des conflits dans les dépendances pis sont pas triviales à corriger, vu que y'a des breaking changes dans une dépendance de di.dart.

2016-10-04 20:31 UTC, meriouma commented on shared/pubspec.yaml
> +  dart_style: 0.2.4
À faire fonctionner dogma. Si on met à jour analyzer, les `@Serialize.field` sont pas pris en compte, et sinon ça plante. C'est la combinaison de analyzer et dart_style qui fonctionnent pour moi :P

2016-10-04 20:31 UTC, meriouma commented on frontend/lib/emojis/emojis.dart
> +        if (0xDC00 <= b && b <= 0xDFFF) {
Haha ouin, cette méthode là je pourais pas dire que c'est moi qui l'a écrite

2016-10-04 20:33 UTC, Pacane commented on shared/pubspec.yaml
> +  dart_style: 0.2.4
Ok cool, j'avais aussi un fuck de dépendances avec dogma. Y'a dogma 2 qui est en train de s'écrire aussi ça l'air. Ben hâte de voir ça va avoir l'air de quoi.

2016-10-05 13:14 UTC, jasonlemay commented on frontend/lib/components/message/message_component.html
>              <p class="message__header__time"><time pubdate datetime="2009-10-10T19:10-08:00">{{formattedDate}}</time></p>
Peux-tu rendre le `datetime` dynamique? Sinon efface le, tant qu'à avoir de la mauvaise info.

2016-10-05 13:20 UTC, Pacane commented on frontend/lib/components/message/message_component.html
>              <p class="message__header__time"><time pubdate datetime="2009-10-10T19:10-08:00">{{formattedDate}}</time></p>
ça fait quoi cet attribut là au juste? Le contenu est dynamique en tout cas avec le `{{formattedDate}}`

2016-10-05 13:22 UTC, Pacane commented on frontend/lib/emojis/emojis.dart
> +  static dynamic getChar(String emojiName) {
Pourquoi ça c'est `dynamic` ? ça retourne une string au final, non?

2016-10-05 13:31 UTC, jasonlemay commented on frontend/lib/components/search/search_component.html
> +            <br class="search-legend__break">
Une classe sur un <br>? Clever.

2016-10-05 13:31 UTC, Pacane commented on frontend/lib/services/query_parser.dart
> +  static final String MENTION = 'mention:';
les constantes devraient être en camel case.

2016-10-05 13:32 UTC, jasonlemay commented on frontend/web/assets/css/_sass/base/_print.scss
> +@charset "UTF-8";
tu ne peux pas simplement le mettre sur le `main.scss` puisqu'il importe toutes les feuilles?

2016-10-05 13:36 UTC, jasonlemay commented on frontend/lib/components/message/message_component.html
>              <p class="message__header__time"><time pubdate datetime="2009-10-10T19:10-08:00">{{formattedDate}}</time></p>
J'imagine que ça aide à l'indexation dans les moteurs de recherche. Mais puisqu'on indexera pas ça, pis que le message anyway vient déjà d'un filtre, on peut enlever `pubdate datetime="2009-10-10T19:10-08:00"` et ne garder que `<time>`

https://arcbees-slack-history.appspot.com/#/

2016-10-05 13:49 UTC, Pacane commented on frontend/lib/components/search/search_component.html
> +            <br class="search-legend__break">
Pour vrai, ou c'est sarcastique?

2016-10-05 13:55 UTC, jasonlemay commented on frontend/lib/components/search/search_component.html
> +            <br class="search-legend__break">
Pour vrai :) J'imagine que c'est mon code. Will reuse!

2016-10-05 13:57 UTC, Pacane commented on frontend/lib/components/search/search_component.html
> +            <br class="search-legend__break">
Oui c'est le tien, je te confirme avec git blame :P

2016-10-05 15:27 UTC, meriouma commented on frontend/web/assets/css/_sass/base/_print.scss
> +@charset "UTF-8";
Je sais pas, j'ai pas essayé, je voulais pas gosser avec ça. C'était le docker build qui plantait

2016-10-05 15:27 UTC, meriouma commented on frontend/lib/emojis/emojis.dart
> +  static dynamic getChar(String emojiName) {
Bonne question!

2016-10-05 16:02 UTC, Pacane commented on backend/pubspec.yaml
> +  mongo_dart: '0.2.9'
Tu veux p-ê upgrader la version vers la nouvelle, celle que je t'ai déployée.

2016-10-05 16:02 UTC, Pacane commented on backend/pubspec.yaml
> +  mongo_dart:
pis enlever ça.

2016-10-07 14:26 UTC, Pacane approved these changes

2016-10-07 14:26 UTC, merged